import importlib
import json
import shutil
import sys
from pathlib import Path

from backtester_engine import execute_trade, calculate_metrics
from data_manager import DataManager


DATA_MANAGER = DataManager("data")

DEFAULT_SYMBOL = "NIFTY"
DEFAULT_TIMEFRAME = "15m"

FRONTEND_DATA_FILE = Path("/home/yuktrix/Music/frontend/data.json")


def iso(value):
    if hasattr(value, "isoformat"):
        return value.isoformat()
    return value


def build_trade_json(trade, trade_id):
    points = float(trade["Points"])
    result = "WIN" if points > 0 else "LOSS" if points < 0 else "BREAKEVEN"

    signal_time = trade["Signal Candle Time (Cn)"]
    entry_time = trade["Entry Candle Time (Cn+1)"]
    exit_time = trade["Exit Time"]
    direction = str(trade.get("Direction", "Long")).upper()

    events = [
        {
            "type": "SIGNAL",
            "time": iso(signal_time),
            "price": float(trade["Signal Candle Close"]),
        },
        {
            "type": "ENTRY",
            "time": iso(entry_time),
            "price": float(trade["Entry"]),
            "direction": direction,
        },
        {
            "type": "STOP_LOSS_LEVEL",
            "time": iso(entry_time),
            "price": float(trade["Stop Loss"]),
        },
        {
            "type": "TARGET_LEVEL",
            "time": iso(entry_time),
            "price": float(trade["Target"]),
        },
        {
            "type": "EXIT",
            "time": iso(exit_time),
            "price": float(trade["Exit Price"]),
            "reason": trade["Exit Reason"].upper(),
        },
    ]

    return {
        "tradeId": trade_id,
        "date": iso(trade["Trade Date"]),
        "direction": direction,
        "gapPct": float(trade.get("Gap %", 0)),
        "pdc": float(trade.get("PDC", 0)),
        "todayOpen": float(trade.get("Today Open", 0)),
        "firstCandleTime": iso(trade.get("First Candle Time", signal_time)),
        "firstCandleHigh": float(trade.get("First Candle High", 0)),
        "signalTime": iso(signal_time),
        "signalPrice": float(trade["Signal Candle Close"]),
        "entryTime": iso(entry_time),
        "entryPrice": float(trade["Entry"]),
        "stopLoss": float(trade["Stop Loss"]),
        "risk": float(trade["Risk"]),
        "rr": float(trade["RR"]),
        "target": float(trade["Target"]),
        "exitTime": iso(exit_time),
        "exitPrice": float(trade["Exit Price"]),
        "exitReason": trade["Exit Reason"],
        "result": result,
        "pnl": points,
        "points": points,
        "events": events,
    }


def build_frontend_data(df, trades, metrics, strategy, symbol, timeframe):
    candles = []

    for _, row in df.iterrows():
        candles.append({
            "time": iso(row["time"]),
            "open": float(row["open"]),
            "high": float(row["high"]),
            "low": float(row["low"]),
            "close": float(row["close"]),
            "volume": None,
        })

    trade_json = [
        build_trade_json(trade, trade_id)
        for trade_id, trade in enumerate(trades, start=1)
    ]

    equity_curve = []
    cumulative = 0.0

    for trade_id, trade in enumerate(trades, start=1):
        points = float(trade["Points"])
        cumulative += points
        equity_curve.append({
            "time": iso(trade["Exit Time"]),
            "tradeId": trade_id,
            "pnl": points,
            "cumulativePnl": cumulative,
        })

    start_date = df.iloc[0]["time"]
    end_date = df.iloc[-1]["time"]

    parameters = {
        "riskReward": getattr(strategy, "RR", 2.0),
    }

    for attr, key in [
        ("CN_START_TIME", "cnStartTime"),
        ("BREAKOUT_CUTOFF_TIME", "breakoutCutoff"),
        ("TIME_EXIT_TIME", "timeExit"),
    ]:
        if hasattr(strategy, attr):
            parameters[key] = getattr(strategy, attr).strftime("%H:%M")

    return {
        "backtest": {
            "symbol": "NIFTY 50",
            "exchange": "NSE",
            "timeframe": timeframe,
            "strategy": strategy.STRATEGY_NAME,
            "startDate": iso(start_date),
            "endDate": iso(end_date),
            "dateRange": {
                "from": iso(start_date),
                "to": iso(end_date),
            },
        },
        "strategy": {
            "name": strategy.STRATEGY_NAME,
            "description": "Results generated by Python backtesting engine.",
            "parameters": parameters,
        },
        "dataset": {
            "source": "1-minute master data",
            "symbol": symbol,
            "timeframe": timeframe,
            "candleCount": len(candles),
            "tradingDays": df["date"].nunique(),
        },
        "candles": candles,
        "trades": trade_json,
        "metrics": {
            "totalTrades": metrics["totalTrades"],
            "wins": metrics["winningTrades"],
            "losses": metrics["losingTrades"],
            "winningTrades": metrics["winningTrades"],
            "losingTrades": metrics["losingTrades"],
            "winRate": metrics["winRate"],
            "grossProfit": metrics["grossProfit"],
            "grossLoss": metrics["grossLoss"],
            "netPnl": metrics["netPnl"],
            "profitFactor": metrics["profitFactor"],
            "maxDrawdown": metrics["maxDrawdown"],
        },
        "equityCurve": equity_curve,
    }


def main():
    if len(sys.argv) < 2:
        print("Usage:")
        print("python run_backtest.py <strategy_name>")
        return

    strategy_name = sys.argv[1]

    try:
        strategy = importlib.import_module(f"strategies.{strategy_name}")
    except ModuleNotFoundError:
        print(f"Strategy not found: {strategy_name}")
        return

    symbol = getattr(strategy, "SYMBOL", DEFAULT_SYMBOL)
    timeframe = getattr(strategy, "TIMEFRAME", DEFAULT_TIMEFRAME)
    timeframes = getattr(strategy, "TIMEFRAMES", [timeframe])

    print()
    print(f"Loading {symbol} {timeframe} data...")

    datasets = DATA_MANAGER.get_multiple(symbol, timeframes)

    df = datasets[timeframe].copy()
    df["date"] = df["time"].dt.date

    trades = []
    trading_days = sorted(df["date"].unique())

    directional = getattr(strategy, "SUPPORTS_DIRECTIONS", False)

    for i in range(1, len(trading_days)):
        current_date = trading_days[i]
        previous_date = trading_days[i - 1]

        day_df = df[df["date"] == current_date].copy()
        previous_day_df = df[df["date"] == previous_date].copy()

        if day_df.empty or previous_day_df.empty:
            continue

        previous_close = float(previous_day_df.iloc[-1]["close"])

        if directional:
            signal = strategy.check_signal(
                day_df,
                previous_close,
                data_manager=DATA_MANAGER,
                datasets=datasets,
            )
        else:
            signal = strategy.check_signal(
                day_df,
                previous_close,
                data_manager=DATA_MANAGER,
                datasets=datasets,
            )

        if signal is None:
            continue

        if directional:
            trade = execute_trade(
                day_df,
                signal["signal_row"],
                rr=strategy.RR,
                direction=signal["direction"],
                stop_loss=signal["stop_loss"],
                time_exit_df=datasets.get("5m"),
                time_exit_time=getattr(strategy, "TIME_EXIT_TIME", None),
            )
        else:
            trade = execute_trade(
                day_df,
                signal["signal_row"],
                rr=strategy.RR,
            )

        if trade is None:
            continue

        trade["Trade Date"] = current_date
        trade["Direction"] = trade.get("Direction", "Long")
        trade["Gap %"] = signal.get("gap_pct", 0)
        trade["PDC"] = previous_close
        trade["Today Open"] = float(day_df.iloc[0]["open"])
        trade["First Candle Time"] = day_df.iloc[0]["time"]
        trade["First Candle High"] = signal.get(
            "first_candle_high",
            signal.get("cn_high", day_df.iloc[0]["high"]),
        )

        trades.append(trade)

    metrics = calculate_metrics(trades)

    frontend_data = build_frontend_data(
        df,
        trades,
        metrics,
        strategy,
        symbol,
        timeframe,
    )

    with open("data.json", "w", encoding="utf-8") as f:
        json.dump(frontend_data, f, indent=2)

    try:
        shutil.copy2("data.json", FRONTEND_DATA_FILE)
        dashboard_updated = True
    except (FileNotFoundError, PermissionError):
        dashboard_updated = False

    print()
    print("=" * 50)
    print(strategy.STRATEGY_NAME)
    print("=" * 50)
    print("Data source:   1-minute master")
    print(f"Symbol:        {symbol}")
    print(f"Timeframe:     {timeframe}")
    print(f"Total candles: {len(df)}")
    print(f"Total trades:  {metrics['totalTrades']}")
    print(f"Wins:          {metrics['winningTrades']}")
    print(f"Losses:        {metrics['losingTrades']}")
    print(f"Win rate:      {metrics['winRate']:.2f}%")
    print(f"Gross profit:  {metrics['grossProfit']:.2f}")
    print(f"Gross loss:    {metrics['grossLoss']:.2f}")
    print(f"Net points:    {metrics['netPnl']:.2f}")
    print(f"Profit factor: {metrics['profitFactor']:.4f}")
    print(f"Max drawdown:  {metrics['maxDrawdown']:.2f}")
    print()
    print("data.json created.")
    print("Dashboard data updated." if dashboard_updated else
          "Dashboard data copy skipped (frontend path unavailable).")
    print("=" * 50)


if __name__ == "__main__":
    main()
